package de.szut.ita13.cs.mavenwithspringtest.database;
// Generated 18.03.2015 10:50:57 by Hibernate Tools 4.3.1



/**
 * KeyvalueExample generated by hbm2java
 */
public class KeyvalueExample  implements java.io.Serializable {


     private Integer id;
     private String pet;

    public KeyvalueExample() {
    }

    public KeyvalueExample(String pet) {
       this.pet = pet;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPet() {
        return this.pet;
    }
    
    public void setPet(String pet) {
        this.pet = pet;
    }




}


